# Setup
title: Frédéric Wang
tagline: Yet another non-exponentially growing weblog
url: https://frederic-wang.fr/
paginate: 1
baseurl: "http://fred-wang.github.io/frederic-wang.fr/"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - poole-for-jekyll-LICENSE.md

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: Frédéric Wang
  url: https://frederic-wang.fr/
